language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep

script: make test

notifications:
    email: false

matrix:
    allow_failures:
        - go: master
