language: go

go:
  - "1.10.x"
  - master

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/securego/gosec/cmd/gosec

script: make test

notifications:
    email: false
